version: '3.8'

services:
  weborca:
    build:
      context: ./
      dockerfile: weborca.Dockerfile
    container_name: weborca-container
    environment:
      ORCA_DBNAME: orca_db
      ORCA_DBUSER: orca_user
      ORCA_DBPASS: orca_pass
      ORCA_DBHOST: postgres
      PGPASSWORD: orca_pass
      ORCA_DBPORT: 5432
    depends_on:
      - postgres
    volumes:
      - ./db.conf.sh:/opt/jma/weborca/conf/db.conf
      - ./weborca-init:/opt/jma/weborca/app/init
      - ./jma-receipt:/etc/jma-receipt
    # command: /bin/bash -c "/opt/jma/weborca/app/bin/jma-setup && systemctl restart jma-receipt-weborca && sleep infinity"

  postgres:
    image: postgres:13
    container_name: postgres-container
    environment:
      POSTGRES_DB: orca_db
      POSTGRES_USER: orca_user
      POSTGRES_PASSWORD: orca_pass
    ports:
      - "5432:5432"
    # volumes:
    #   - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
